; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32_HW_Ver_1_1]
platform = espressif32 @ ^6.13.0
platform_packages = 
  framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#release/v2.x
board = esp32dev
framework = arduino
lib_deps = 
    FS
    SPIFFS
    WiFi
    CAN
    Lawicel
    WebServer
    Web
    https://github.com/BlueAndi/AsyncTCPSock#feature/Arduino3.x.x
    ESP32Async/ESPAsyncWebServer @ ^3.8.1
build_flags=
    -Wall
    -Wextra
    -O3
    -Wl,-Map,firmware.map
    -I./src/Adapters
    -D SOC_WIFI_SUPPORTED=1 ; AsyncWebserver requires this. Can be removed with Arduino 3.x.x
    -D CONFIG_ASYNC_TCP_RUNNING_CORE=APP_CPU_NUM
    -D CONFIG_ASYNC_TCP_USE_WDT=1
    -D CONFIG_ASYNC_TCP_STACK_SIZE=8192
build_unflags = 
    -Os
    -g3
lib_ignore =
    Test
    AsyncTCP
    ESPAsyncTCP
    RPAsyncTCP
monitor_speed = 115200

[env:native]
platform = native
build_flags =
    -std=c++11
    -DARDUINO=100
    -DPROGMEM=
    -DNATIVE
lib_deps = 
lib_ignore =
    IO
    CAN
    Web
    Settings