@startuml
Title Application Diagram (WebServer)

Class Application

package WebServer <<node>>
{
    Class WebConfig
    Class Pages
    Class CaptivePortal

    Application *.. ESPServer
    ESPServer 	*-- WebConfig : <<use>>
    ESPServer 	*-- Pages : <<use>>
    ESPServer 	*-- CaptivePortal : <<use>>
    ESPServer 	*-- WebSocket : <<use>>
}

package Espressif_ESP32_Library{
    Class Settings{

        -Preferences flashMemory
    }
    Class SPIFFS

    WebConfig --> Settings : <<use>>
    Pages o-- SPIFFS : <<use>>
    CaptivePortal o-- SPIFFS : <<use>>
}

package ESPAsyncWebServer <<folder>>
{
    Class AsyncWebServer
}

WebServer 	o-- ESPAsyncWebServer : <<use>>

@enduml