@startuml

title WiFi-Mode Button \n

start

:Turn on WiFi-Mode LEDs.;

note left
    Signals Setup-time 
    to choose a WiFi-Mode
end note

repeat

    if (Button Pressed) then (yes)

        :Increase "Pressed" counter;


    else (no)

        :Increase "Released" counter;

    endif

repeat while (5 Seconds)

:Turn on WiFi-Mode LEDs.;

:Define WiFi-Mode.;

note left
    Mode defined through
    comparison of counters.
end note

:Turn on correct WiFi-Mode LED.;

stop

@enduml