@startuml

title CAN-Controller State Machine \n

start

:Initialize CAN-Controller.;
:Define CAN-Bus speed.;

if(Succesful?) then (yes)
    repeat
        repeat
        repeat while (Bus-Off Requested)
        ->no;

        Partition Receiver {
            :Listen for incoming Packet.;
            :Parse Packet.;
            :Add Packet to Log.;
            if (Is Packet a Remote Transmission Request?) then (yes)
                :Queue Response Frame.;
            else(no)
            endif
        }

        Partition Sender {

            if (Check if there are frames to send) then (yes)
                :Begin Packet.;
                :Write Information.;
                :Send Packet.;
            else(no)
            endif
        }

    repeat while (CAN-Bus Terminated?) is (no)
    ->yes;
    stop

else(no)
    :Error State.;
    ->wait for restart;
    stop
endif
@enduml