@startuml

title Hierarchy Diagram

node {
    package Application{
        component ESP_CAN_Analyzer as ESP_CAN
    }

    package Modules{
        component ESPAsyncServer
        component Lawicel
        component CAN
        component AsyncTCP
    }

    package Service{
        component IP_Stack
        component ESP32SJA1000
        component Board
    }



    package HAL {
        component Arduino
        component SoftwareSerial
        component WiFi
        component GPIO
        component CANController
    }
    package Hardware{
        component USB_Serial
        component GPIO
        component Wifi_Antenna
        component CAN_Transceiver
    }
}
interface Webserver
interface USB
interface DSUB9
interface Button
interface LEDs
component Laptop
component CAN_BUS


USB_Serial --> USB
GPIO --> Button
GPIO --> LEDs
Wifi_Antenna --> Webserver
CAN_Transceiver --> DSUB9
Laptop --( Webserver
Laptop --( USB
CAN_BUS --( DSUB9


Arduino --> SoftwareSerial
Arduino --> WiFi
Arduino --> GPIO

SoftwareSerial --> USB_Serial
WiFi --> Wifi_Antenna

Lawicel --> CAN
IP_Stack --> Arduino
CANController --> CAN_Transceiver

ESPAsyncServer --> AsyncTCP
AsyncTCP --> IP_Stack
Arduino --> CANController
ESP32SJA1000 --> Arduino

CAN --> ESP32SJA1000
Board --> Arduino
ESP_CAN --> Board

ESP_CAN --> Lawicel
ESP_CAN --> ESPAsyncServer


@enduml