@startuml

title ESP CAN-Bus Adapter

component "External CAN/OBD-II Bus" as CANBUS
component "External Power Supply" as ExtPower

interface "DSUB-9" as DSUB
interface "USB" as usb

package "Housing" {

    package "Power Supply" as PowerSupply{

        }

    package "PCB" as pcb {

        

        package "CAN Transceiver" as Transceiver{

        }

        package "ESP32 DevKitV1 connector" {

            component "ESP32 DevKitV1" as esp32
        }

        interface "JTAG" as iJtag

        esp32 -u- iJtag

        interface "GPIO" as GPIO

        component "WiFi Mode Button" as userButton
        component "Reset Button" as resetButton
    }
}

CANBUS --( DSUB
DSUB -right- PowerSupply : 12V VCC
DSUB -- Transceiver : Data

ExtPower --( usb
usb -- PowerSupply : 5V


PowerSupply -- pcb : VCC + Pin Select

esp32 -- Transceiver
esp32 -- userButton: input
esp32 -- resetButton: reset
esp32 -- GPIO : input/output

@enduml