@startuml

title Hierarchy Diagram





node {
    package Application{
        component HTTP_Server
        component ESP_CAN
        component Lawicel
    }

    package HAL{
        component Arduino_h
        component ESPAsyncServer
        component ESP32SJA1000_h
    }

    package Hardware{
        component USB_Serial
        component GPIO
        component Wifi_Antenna
        component CAN_Transceiver
    }
}
interface Webserver
interface USB
interface DSUB9
interface Button
interface LEDs
component Laptop
component CAN_BUS


USB_Serial --> USB
GPIO --> Button
GPIO --> LEDs
Wifi_Antenna --> Webserver
CAN_Transceiver --> DSUB9
Laptop --( Webserver
Laptop --( USB
CAN_BUS --( DSUB9

Arduino_h --> USB_Serial
Arduino_h --> GPIO
ESPAsyncServer --> Wifi_Antenna
ESP32SJA1000_h --> CAN_Transceiver

Lawicel --> Arduino_h
HTTP_Server --> ESPAsyncServer
ESP_CAN --> ESP32SJA1000_h

ESP_CAN --> Lawicel
ESP_CAN --> HTTP_Server


@enduml