@startuml

title Hierarchy Diagram

node {
    package Application{
        component Webpages
        component ESP_CAN_Analyzer as ESP_CAN

    }

    package ?{
        component ESPAsyncServer
        component Lawicel_h
        component CAN_h
        component AsyncTCP
    }

    package Service{
        component IP_Stack
        component ESP32SJA1000_h
    }



    package HAL {
        component Arduino_h
        component SoftwareSerial_h
        component WiFi_h
        component GPIO_h
        component CANController_h
    }
    package Hardware{
        component USB_Serial
        component GPIO
        component Wifi_Antenna
        component CAN_Transceiver
    }
}
interface Webserver
interface USB
interface DSUB9
interface Button
interface LEDs
component Laptop
component CAN_BUS


USB_Serial --> USB
GPIO --> Button
GPIO --> LEDs
Wifi_Antenna --> Webserver
CAN_Transceiver --> DSUB9
Laptop --( Webserver
Laptop --( USB
CAN_BUS --( DSUB9


Arduino_h --> SoftwareSerial_h
Arduino_h --> WiFi_h
Arduino_h --> GPIO_h

SoftwareSerial_h --> USB_Serial
WiFi_h --> Wifi_Antenna
GPIO_h --> GPIO

Lawicel_h --> CAN_h
IP_Stack --> Arduino_h
CANController_h --> CAN_Transceiver

ESPAsyncServer --> AsyncTCP
AsyncTCP --> IP_Stack
Arduino_h --> CANController_h
ESP32SJA1000_h --> Arduino_h


Webpages --> ESPAsyncServer
CAN_h --> ESP32SJA1000_h

ESP_CAN --> Lawicel_h
ESP_CAN --> Webpages


@enduml