@startuml

Title Mainloop Sequence

group Setup
    Mainloop --> Board : init()
    Board --> Mainloop
    Mainloop --> Lawicel : begin()
    Lawicel --> Lawicel : Set up Adapters

    alt WebSocket Adapter Configured
        Lawicel --> ESPServer : begin()
        ESPServer --> WebConfig : importSettings()
        WebConfig --> ESPServer : return bool success
        ESPServer --> WLAN : begin()
        WLAN --> Board : checkUserButton()
        Board --> WLAN : return bool buttonPressed
        WLAN --> WLAN : Initialize selected \nWiFi Mode
        WLAN --> ESPServer : return bool success
        ESPServer --> ESPServer : Set up Web Pages
        ESPServer --> Lawicel : return bool success
    end

    Lawicel --> Mainloop : return bool success

    else Initialization returns false

    Mainloop --> Board : set Error LED \nand System halt
    Board --> Board : wait for error handling\nfrom user and restart
end

group loop
    Mainloop --> Lawicel : executeCycle()
    Lawicel --> Mainloop : return bool success

    Mainloop --> WLAN : Check Connection Status
    WLAN --> Mainloop : return bool success

    else Restart requested
    ESPServer --> Mainloop : restart()
    Mainloop --> Lawicel : end()
    Mainloop --> ESPServer : end()
    Mainloop --> Board : esp.restart()
end

@enduml