@startuml
title Startup

start
:Initialize hardware.;
:Check user button state.;

if (Is pressed?) then (yes)

    :Check WiFi Credentials.;

    if (Is available?) then (yes)

        if (Connection successful established?) then (yes)

        else (no)
            :Set Error LED.;
            stop
        endif

    else(no)
        :Set Error LED.;
        stop

    endif

else(no)

    :Setting up access-point (AP).;

    if (successful?) then (no)
        :Set Error LED.;
        stop
    else (yes)
    endif

endif

:Start CAN-Controller to desired Bus Speed.;
if (successful) then (yes)
    stop
else(no)
    :Set Error LED.;
    stop

    @enduml