@startuml

title System State Machine

InitState: /entry: Initialize Modules.
InitState: /do: Get button state.

APState: /entry: Setup access point.
APState: /entry: Setup Captive Portal.
APState: /entry: Start server.
APState: /do: Handle client requests.
APState: /do: Save new Credentials when given by user.
APState: /exit: Stop server.
APState: /exit: Shutdown access point.

ConnectingState: /entry: Get Access Point SSID and Password.
ConnectingState: /do: Connect to Network.

STAState: /entry: Setup Webpages.
STAState: /entry: Setup Websocket.
STAState: /entry: Start server.
STAState: /do: Handle client requests.
STAState: /do: Handle CAN-Controller
STAState: /exit: Stop CAN-Controller
STAState: /exit: Stop server.

ErrorState: /do: Wait for manual reset.


[*] --> InitState: Power up
InitState --> APState: [Button pressed]
InitState -> ConnectingState: [Button released]
APState --> ErrorState: [Failed to start\nwifi access point]
STAState --> ErrorState: [Remote wifi SSID or\npassword missing]
ConnectingState --> STAState: [Connection successful established]
STAState --> ConnectingState: [Connection lost]
ConnectingState --> ErrorState : [Timeout]
ErrorState --> [*]: [Restart]
@enduml