@startuml

title System State Machine

InitState: /entry: Initialize HAL.
InitState: /do: Get button state.

APState: /entry: Setup access point.
APState: /entry: Start server.
APState: /do: Handle client requests.
APState: /do: Handle CAN-Controller
APState: exit/: Stop CAN-Controller
APState: /exit: Stop server.
APState: /exit: Shutdown access point.

ConnectingState: /entry: Get remote WiFi SSID and passphrase.
ConnectingState: /do: Connect every 30 s to remote WiFi network.

STAState: /entry: Start server.
STAState: /do: Handle client requests.
STAState: /do: Handle CAN-Controller
STAState: exit/: Stop CAN-Controller
STAState: /exit: Stop server.

ErrorState: /do: Wait for manual reset.

RestartState: /entry: Unmount filesystem
RestartState: /do: Restart

[*] --> InitState: Power up
InitState --> APState: [Button released]
InitState -> ConnectingState: [Button pressed]
APState --> ErrorState: [Failed to start\nwifi access point]
APState --> RestartState: [Update finished]
STAState --> ErrorState: [Remote wifi SSID or\npassword missing]
ConnectingState --> STAState: [Connection successful established]
STAState --> ConnectingState: [Connection lost]
STAState --> RestartState: [Update finished]
ErrorState --> [*]: [Restart]
RestartState --> [*]: [Restart]
@enduml