@startuml

title System State Machine

InitState: /entry: Initialize Board.
InitState: /do: Get "WiFi _Mode" Button state.
InitState: /do: Initialize Lawicel and its Adapters.

AP_Mode: /entry: Setup Access Point.
AP_Mode: /entry: Setup Captive Portal.
AP_Mode: /entry: Start server.
AP_Mode: /do: Handle client requests.
AP_Mode: /do: Save new Credentials when given by user.
AP_Mode: /exit: Stop server.
AP_Mode: /exit: Shutdown access point.

STA_Mode: /entry: Retrieve Access Point SSID and Password from NVM.
STA_Mode: /entry: Connect to Network.
STA_Mode: /entry: Setup Webpages.
STA_Mode: /entry: Setup Websocket.
STA_Mode: /entry: Start server.
STA_Mode: /do: Handle client requests.
STA_Mode: /do: Handle Lawicel Cycle.

ErrorState: /do: Wait for manual reset.


[*] --> InitState: Power up
InitState --> AP_Mode: [Button is pressed]
InitState --> STA_Mode: [Button is released]
AP_Mode --> ErrorState: [Failed to start\nwifi access point]
STA_Mode --> ErrorState: [Failed to connect \nto user's Network]
ErrorState --> [*]: [Restart]
AP_Mode --> [*]: [Restart]
@enduml