@startuml

Title Webserver Class Diagram

class ESP_WebServer
class Settings
class WebConfig
class Pages
class CaptivePortal

ESP_WebServer --> Pages 
ESP_WebServer --> CaptivePortal 

WebConfig --> Settings 
ESP_WebServer --> WebConfig 
Pages --> WebConfig 
CaptivePortal --> WebConfig 
CaptivePortal --> Settings 

@enduml